### ISSUE TITLE
server.reload (from wait_for)

### ISSUE THREAD

**Issue by matburstorm** [fog/fog-azure#26]
Hi, I'm trying to wait for a server to spin up with the standard server.wait_for {} method. It seems that it is calling fog/reload which then calls azure/get which has a non-standard number of argument (= 2) which
causes fog core to die. I patched my local copy with this:

```
def get(identity, cloud_service_name=nil)
      cloud_service_name = identity unless cloud_service_name
      all.find { |f| f.name == identity && f.cloud_service_name == cloud_service_name }
    rescue Fog::Errors::NotFound
      nil
    end
```

   end

which causes reload to work again, but I'm not really sure if this is just a hack or is an actual
solution. 

Here's the backtrace:

/var/lib/gems/2.0.0/gems/fog-azure-0.0.2/lib/fog/azure/models/compute/servers.rb:44:in `get': wrong number of arguments (1 for 2) (ArgumentError)
    from /var/lib/gems/2.0.0/gems/fog-core-1.38.0/lib/fog/core/model.rb:43:in`reload'
    from /var/lib/gems/2.0.0/gems/fog-core-1.38.0/lib/fog/core/model.rb:70:in `block in wait_for'
    from /var/lib/gems/2.0.0/gems/fog-core-1.38.0/lib/fog/core/wait_for.rb:7:in`block in wait_for'
    from /var/lib/gems/2.0.0/gems/fog-core-1.38.0/lib/fog/core/wait_for.rb:6:in `loop'
    from /var/lib/gems/2.0.0/gems/fog-core-1.38.0/lib/fog/core/wait_for.rb:6:in`wait_for'
    from /var/lib/gems/2.0.0/gems/fog-core-1.38.0/lib/fog/core/model.rb:69:in `wait_for'
    from /home/mike/burstorm/perfrun/perfrun/drivers/azure.rb:46:in`create_server'
    from ./rsutils:41:in `<main>'

cheers, Mike

**Comment by dLobatog** [comment]
The issue seems to be that `get` in servers.rb is defined to take 2 arguments (identity and cloud service name), otherwise Azure does not provide an UUID. I would say providing at least a default where `cloud_service_name == identity` would be nice.
