### ISSUE TITLE
Fog compute error for azure

### ISSUE THREAD

**Issue by shruthirajk** [fog/fog-azure#28]
I am a beginner in ruby.I have a sample code for azure connect in ruby.
require 'fog'
require 'pp'
require 'azure'
require 'fog-azure'

module Fog
  module Compute

class Azure < Fog::Compute.new(
  :provider => 'Azure',
  :azure_sub_id => 'sub_id ',
  :azure_pem => '/home/test/Azureuser.pem',
  :publish_method => 'AzureServiceManagementAPI',
  :azure_access_keys => 'access_key',

)
end
end
end
# **I get the below error:**

/usr/local/lib/ruby/1.9.1/yaml.rb:84:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in`require': cannot load such file -- fog-azure (LoadError)
        from /usr/local/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from azure_test.rb:6:in`<main>'
If anyone could help me in resolving this issue.

**Comment by aheumaier** [comment]
Use  
```
require 'fog/azure'
```
to load internal lib
